In [1]:
import pandas as pd
from pyproj import Proj, transform
from geopy.geocoders import Nominatim
import pyproj
import time
import re
import numpy as np
from tqdm import tqdm
from geopy.exc import GeocoderTimedOut
import math

In [2]:
#Unidae comercial
und = pd.read_csv("unidade_comercial.csv", encoding='latin1', delimiter='\t')
und.columns

und['Número'] = np.nan
und['Latitude'] = np.nan
und['Longitude'] = np.nan

C:\Users\Projeto 7\AppData\Local\Temp\ipykernel_14268\939843541.py:2: DtypeWarning: Columns (23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  und = pd.read_csv("unidade_comercial.csv", encoding='latin1', delimiter='\t')

In [3]:
pd.set_option('display.max_rows', None)
und['Serviço Executado'].value_counts()

Serviço Executado
800 - RECADASTRAMENTO                                          4981
801 - RECADASTRAMENTO EXECUTADO                                4910
813 - ALTERAR DADOS DA LIGACAO - RECADASTRAMENTO               3698
24 - AC - Emissao 2 Via de Fatura                              2925
810 - ALTERACAO DADOS CADASTRAIS - RECADASTRAMENTO             2675
802 - RECADASTRAMENTO 2º VISITA                                1089
3101 - LA - Relig/Corte Cav.                                    769
812 - ALTERAR DADOS DE FONTE PROPRIA - RECADASTRAMENTO          647
3100 - LA - Corte Cav. Falta Pagamento                          640
5002 - AC - Alterar Cliente Unidade Comercial                   562
2222 - CANCELAR PARCELA LIXO - BOLETO                           537
811 - ALTERACAO CATEGORIA/ECONOMIA - RECADASTRAMENTO            329
814 - ALTERAR ENDERECO PRINCIPAL - RECADASTRAMENTO              327
2020 - LA -  Conserto Ramal                                     254
5028 - CAD -  Alterar Dados Endereco Unidade Comercial          235
1020 - LA - Conserto Cavalete antes Hidrometro                  176
1040 - LA - Deslocamento Cavalete 1/2" e  3/4" I.E.             157
8888 - VERIFICAR ACESSO CAVALETE                                156
5022 - CAD - Verificacao Cadastral - Nova Unidade               124
3001 - INSTALACAO NOVA LIGACAO RESIDENCIAL OU COMERCIAL         123
6008 - FAT - Alteracao de Fatura - Ajuste Consumo/Vazamento     110
5100 - FIS - Verificacao de Irregularidade/vazamento            107
1512 - LA - Substituicao Hidrometro I.E.                         95
122 - ALTERAR DADOS DE FATURAMENTO DE LIXO                       75
6201 - AC -  Parcelamento Fatura                                 64
1010 - LA - Troca de Registro do Cavalete                        62
77 - LA CORTE CAV. FALTA PAGAMENTO/PARCELAMENTO                  58
1019 - Conserto de cavalete apos HD / SEM ONUS                   46
303 - CONTRIBUICAO ESPONTANEA BOMBEIROS SCHROEDER                36
1015 - VERIFICAR MECANISMO HD / LEITURA PARADA                   34
13 - Atualizar Dados Cliente Unidade Comercial                   33
5020 - CAD - Verificacao para Tarifa Social                      30
803 - RECADASTRAMENTO 3º VISITA                                  28
6004 - AC - Alt. Fat. Erro Leitura                               26
4006 - LA - Verificar Irregularidade                             26
114 - ALTERACAO DE ROTA DA UNIDADE                               23
5010 - AC - Alt. Cad. Localizacao                                22
6100 - INTERRUPCAO DE FORNECIMENTO - CORTE CAVALETE. P.U         22
6014 - AC - Alt. Fat. Tipo Categorias                            21
5006 - AC - Alt. Cad. Numero/Economias                           19
6016 - Alterar Data Vencimento Fatura Uniadade Comercial         19
4000 - LA - Verificar Falta de Agua                              19
82 - ARR CANCELAR COMUNICADO DE DEBITO                           18
5021 - CAD. ALTERACAO DE CATEGORIA                               16
54 - ARR - Incluir Valor a Compensar                             15
53 - ARR - Liberar/Bloquear Valor Compensar                      15
94 - Troca do Endereco Principal da Unidade Comercial            15
20 - VERIFICAR CATEGORIA                                         15
1515 - VERIFICAR MECANISMO / LEITURA PARADA OU VOLTANDO          13
304 - CONTRIBUICAO APAE DE SCHROEDER                             13
5200 - FAT - Verificar Leitura                                   13
6101 - RELIGACAO P.U ( INTERRUPCAO/ CORTE P.U)                   13
1016 - VERIFICAR CONSUMO                                         12
46 - FAT - Cancelar Fatura                                       12
1234 - VERIFICAR REGULARIDADE COBRANCA DE LIXO                   10
2309 - VERIFICAR UNIDADE CORTADA                                 10
5016 - CAD - Eliminar Cadastro Debito em Conta                   10
1042 - RETIRAR CAVALETE/ HD  DA CAIXA PADRAO                     10
3333 - VERIFICAR CASA DESOCUPADA                                  9
6018 - AC -  Alt. Fat. Lancamento Indevido/Servico                8
5517 - INF - Violacao Corte Cavalete                              7
5004 - CAD - Alterar Vencimento Alternativo                       7
4002 - LA - Verificar Pressao d'Agua                              6
1508 - FIS - Instalacao de Lacres do Cavalete                     6
3304 - LA - Corte RP Retirada HD. P.U.                            5
1041 - LA - Deslocamento Cavalete 1/2" e 3/4" P.U.                5
161 - ALTERACAO DE FATURA - COBRANCA DE AGUA/ESGOTO               4
6204 - EXCLUIR FATURA DIVIDA ATIVA                                4
22 - AC - Gerar Conta Final                                       4
86 - IDENTIFICAR PAGAMENTO DE FATURA                              3
1018 - LA_ Limpeza da peneira do cavalete                         3
80 - FAT CANCELAMENTO COBRANCA SERVICO A FATURAR                  3
138 - Gerar Comunicado de Debito Manualmente                      3
3300 - LA -  Corte RP. Retirada I.E.                              3
1222 - INSTALACAO DE VENTOSA                                      3
5521 - INF - Ligacao Clandestina/ direta / By Pass                3
200 - ALTERAR VENCIMENTO COBRANCA DE SERVICO                      3
49 - VIABILIDADE DE INCLUSAO / EXCLUSAO DE ECONOMIA               3
1021 - LA - Conserto Cavalete com cobranca                        2
1000003 - ALTERAR FATURA DADOS DE CADASTRO INCORRETO              2
6006 - AC - Alt. Fat. Erro de Consumo                             2
79 - AC ANTECIPACAO PGTO. PARCELAS PARCELAMENTO                   2
1511 - INSTALACAO DE HIDROMETRO - I E                             2
70 - ARR - Transferencia de Pagamento                             2
1000 - Informacoes Diversas                                       1
3400 - LA - Corte de Ligacao Clandestina/ direta / By Pass        1
3102 - LA - Religacao Corte Cavalete - Corte Indevido             1
5026 - CAD -  Excluir Endereco Unidade Comercial                  1
2052 - LA - Substituicao de Ramal I.E.                            1
62 - CAD - Alterar Estrutura Organica                             1
1812 - RETIRADA DE RAMAL                                          1
2021 - LA -  Conserto Ramal - Portal                              1
1520 - LA -  Retirada Hidr. I.E.                                  1
75 - AC - Cancelamento Parcelamento de Debito                     1
84 - FAT - Reenviar Fatura Debito em Conta                        1
4014 - VAZAMENTO COLAR DE LIGACAO- UNIDADE                        1
1514 - LA Desinversao de Hidrometro                               1
Name: count, dtype: int64

In [4]:
pd.set_option('display.max_rows', 10)
und = und[und['Serviço Executado'].str.startswith('4000') | und['Serviço Executado'].isnull()]
und['Categoria de serviço'] = 'Falta de água'

In [5]:
und

,Data de Solicitação,Número da OS,Código Logradouro,Endereço,Ponto de Referência,Bairro,Município,Matrícula,Situação Ligação Água,Serviço Solicitado,...,Data Final da Suspensão por Controle,Motivo da Suspensão por Controle,Parecer da Suspensão por Controle,Período de Suspensão por Controle (dias - horas:min:seg),Data Final da Liberação,Parecer da Liberação,Número,Latitude,Longitude,Categoria de serviço
6,02/01/2023 15:55:00,115757,287,Rua 182 - OTTO VOLLES 291 - Rio Hern -,NaN,Rio Hern,NaN,1366026-8,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
65,06/01/2023 09:54:00,115821,287,Rua 182 - OTTO VOLLES 253 - Rio Hern -,NaN,Rio Hern,NaN,1353886-1,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
67,06/01/2023 10:12:00,115823,48,R. GUAIBA 64 - Rio Hern -,NaN,Rio Hern,NaN,753284-9,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
347,11/01/2023 13:13:00,116115,49,R. ERICH FROEHNER 3978 - Schroeder I . - Sala...,NaN,Schroeder I .,NaN,1369009-4,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
1174,09/02/2023 11:06:00,116979,346,Rua ESTRADA DUAS MAMAS 4962 - Duas Mamas - CX ...,NaN,Duas Mamas,NaN,1368366-7,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13484,25/05/2023 15:46:00,159880,307,Rua 573- VERONICA WELTER 156 - Schroeder I -,NaN,Schroeder I,NaN,1365896-4,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
17282,19/06/2023 15:10:00,178079,10,R. Santa. Catarina 15 - Braco do Sul -,NaN,Braco do Sul,NaN,1369024-8,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
20006,30/06/2023 10:13:00,181364,3,R. Duque de Caxias 381 - Centro Norte -,NaN,Centro Norte,NaN,801221-0,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
29384,08/09/2023 14:21:00,192215,7,R. PRES. COSTA E SILVA 1291 - Rio Hern -,NaN,Rio Hern,NaN,1354221-4,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água
33715,28/11/2023 14:08:00,196594,168,R. MARIO BAGATOLLI 1015 - Schroeder I . - UNI...,NaN,Schroeder I .,NaN,1368570-8,NaN,4000 - LA - Verificar Falta de Agua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Falta de água

In [6]:
und = und[['Matrícula','Categoria de serviço','Data de Solicitação','Endereço','Bairro','Número','Latitude','Longitude']]
und.to_csv("Unidade comercial tratado.csv",sep=';',encoding = 'latin1')
und

,Matrícula,Categoria de serviço,Data de Solicitação,Endereço,Bairro,Número,Latitude,Longitude
6,1366026-8,Falta de água,02/01/2023 15:55:00,Rua 182 - OTTO VOLLES 291 - Rio Hern -,Rio Hern,NaN,NaN,NaN
65,1353886-1,Falta de água,06/01/2023 09:54:00,Rua 182 - OTTO VOLLES 253 - Rio Hern -,Rio Hern,NaN,NaN,NaN
67,753284-9,Falta de água,06/01/2023 10:12:00,R. GUAIBA 64 - Rio Hern -,Rio Hern,NaN,NaN,NaN
347,1369009-4,Falta de água,11/01/2023 13:13:00,R. ERICH FROEHNER 3978 - Schroeder I . - Sala...,Schroeder I .,NaN,NaN,NaN
1174,1368366-7,Falta de água,09/02/2023 11:06:00,Rua ESTRADA DUAS MAMAS 4962 - Duas Mamas - CX ...,Duas Mamas,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
13484,1365896-4,Falta de água,25/05/2023 15:46:00,Rua 573- VERONICA WELTER 156 - Schroeder I -,Schroeder I,NaN,NaN,NaN
17282,1369024-8,Falta de água,19/06/2023 15:10:00,R. Santa. Catarina 15 - Braco do Sul -,Braco do Sul,NaN,NaN,NaN
20006,801221-0,Falta de água,30/06/2023 10:13:00,R. Duque de Caxias 381 - Centro Norte -,Centro Norte,NaN,NaN,NaN
29384,1354221-4,Falta de água,08/09/2023 14:21:00,R. PRES. COSTA E SILVA 1291 - Rio Hern -,Rio Hern,NaN,NaN,NaN
33715,1368570-8,Falta de água,28/11/2023 14:08:00,R. MARIO BAGATOLLI 1015 - Schroeder I . - UNI...,Schroeder I .,NaN,NaN,NaN